import pyyedplus
#
g = pyyedplus.Graph()
#
##A Group
netz = g.add_group('A')
netz.add_node('BCA', shape='ellipse')
netz_A1 = netz.add_group('A1')
netz_A1.add_node('BCA1', shape='ellipse')
netz_A2 = netz.add_group('A2')
netz_A2.add_node('BCA2', shape='ellipse')
netz_A3 = netz.add_group('A3')
netz_A3.add_node('BCA3', shape='ellipse')
netz_A4 = netz.add_group('A4')
netz_A4.add_node('BCA4', shape='ellipse')
netz_A2.add_node('11.0.0.0/24')
netz_A2.add_node('11.0.1.0/24')
netz_A2_srvs = netz_A2.add_group('SRVs@11.0.0.0/24', shape='ellipse')
netz_A2_srvs.add_node('dns.a.net')
netz_A2_srvs.add_node('www.a.net')
netz_A2_srvs.add_node('dc1.a.net')
netz_A2_srvs2 = netz_A2.add_group('SRVs@11.0.1.0/24', shape='ellipse')
netz_A2_srvs2.add_node('chat.a.net')
netz_A2.add_edge('11.0.0.0/24', 'SRVs@11.0.0.0/24', arrowhead='none')
netz_A2.add_edge('11.0.1.0/24', 'SRVs@11.0.1.0/24', arrowhead='none')
netz_A2.add_edge('BCA2', '11.0.0.0/24', arrowhead='none')
netz_A2.add_edge('BCA2', '11.0.1.0/24', arrowhead='none')
netz_A2.add_edge('dc1.a.net', 'chat.a.net', arrowhead='none', line_type='dashed' )
netz.add_edge('BCA','BCA2', arrowhead='none')
netz.add_edge('BCA','BCA1', arrowhead='none')
netz.add_edge('BCA','BCA3', arrowhead='none')
netz.add_edge('BCA','BCA4', arrowhead='none')
# Z Group (A Group alike)
netz = g.add_group('Z')
netz.add_node('BCZ', shape='ellipse')
netz_Z1 = netz.add_group('Z1')
netz_Z1.add_node('BCZ1', shape='ellipse')
netz_Z2 = netz.add_group('Z2')
netz_Z2.add_node('BCZ2', shape='ellipse')
netz_Z3 = netz.add_group('Z3')
netz_Z3.add_node('BCZ3', shape='ellipse')
netz_Z4 = netz.add_group('Z4')
netz_Z4.add_node('BCZ4', shape='ellipse')
netz_Z2.add_node('10.0.0.0/24')
netz_Z2.add_node('10.0.1.0/24')
netz_Z2_srvs = netz_Z2.add_group('SRVs@10.0.0.0/24', shape='ellipse')
netz_Z2_srvs.add_node('dns.z.net')
netz_Z2_srvs.add_node('www.z.net')
netz_Z2_srvs.add_node('dc1.z.net')
netz_Z2_srvs2 = netz_Z2.add_group('SRVs@10.0.1.0/24', shape='ellipse')
netz_Z2_srvs2.add_node('chat.z.net')
netz_Z2.add_edge('10.0.0.0/24', 'SRVs@10.0.0.0/24', arrowhead='none')
netz_Z2.add_edge('10.0.1.0/24', 'SRVs@10.0.1.0/24', arrowhead='none')
netz_Z2.add_edge('BCZ2', '10.0.0.0/24', arrowhead='none')
netz_Z2.add_edge('BCZ2', '10.0.1.0/24', arrowhead='none')
netz_Z2.add_edge('dc1.z.net', 'chat.z.net', arrowhead='none', line_type='dashed' )
netz.add_edge('BCZ','BCZ2', arrowhead='none')
netz.add_edge('BCZ','BCZ1', arrowhead='none')
netz.add_edge('BCZ','BCZ3', arrowhead='none')
netz.add_edge('BCZ','BCZ4', arrowhead='none')
#
g.add_node('BC', shape='ellipse')
g.add_edge('BC','BCA', arrowhead='none')
g.add_edge('BC','BCZ', arrowhead='none')
g.add_edge('chat.a.net','chat.z.net', arrowhead='none', line_type='dotted', width="2.0")
#
g.write_graph('az.graphml', pretty_print=True)
